Traceback (most recent call last):
  File "/Users/morenolq/miniconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/morenolq/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1253, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/morenolq/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/morenolq/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/morenolq/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/morenolq/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 693, in async_execute
    await self.async_execute_cell(
  File "/Users/morenolq/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1010, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/morenolq/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 904, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from torch.utils.data import Dataset

class MyDataset(Dataset):
    '''
    Template class for creating a dataset in PyTorch.
    '''
    
    def __init__(self, **kwargs):
        # Initialize the dataset
        pass

    def __len__(self):
        # Return the size of the dataset
        pass

    def __getitem__(self, idx):
        # Return the sample at the given index
        pass
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtorch[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdata[39;00m [38;5;28;01mimport[39;00m Dataset
[1;32m      3[0m [38;5;28;01mclass[39;00m [38;5;21;01mMyDataset[39;00m(Dataset):
[1;32m      4[0m [38;5;250m    [39m[38;5;124;03m'''[39;00m
[1;32m      5[0m [38;5;124;03m    Template class for creating a dataset in PyTorch.[39;00m
[1;32m      6[0m [38;5;124;03m    '''[39;00m

File [0;32m~/miniconda3/lib/python3.9/site-packages/torch/__init__.py:197[0m, in [0;36m<module>[0;34m[0m
[1;32m    195[0m     [38;5;28;01mif[39;00m USE_GLOBAL_DEPS:
[1;32m    196[0m         _load_global_deps()
[0;32m--> 197[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mtorch[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_C[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m  [38;5;66;03m# noqa: F403[39;00m
[1;32m    199[0m [38;5;66;03m# Appease the type checker; ordinarily this binding is inserted by the[39;00m
[1;32m    200[0m [38;5;66;03m# torch._C module initialization code in C[39;00m
[1;32m    201[0m [38;5;28;01mif[39;00m TYPE_CHECKING:

[0;31mImportError[0m: dlopen(/Users/morenolq/miniconda3/lib/python3.9/site-packages/torch/_C.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libtorch_cpu.dylib
  Referenced from: <BA93ABA0-52DE-3A68-8181-9B1B82C6F0AF> /Users/morenolq/miniconda3/lib/python3.9/site-packages/torch/lib/libtorch_python.dylib
  Reason: tried: '/Users/morenolq/miniconda3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib' (no such file), '/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/Users/morenolq/miniconda3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib' (no such file), '/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/Users/morenolq/miniconda3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib' (no such file), '/Users/morenolq/miniconda3/bin/../lib/libtorch_cpu.dylib' (no such file), '/Users/morenolq/miniconda3/bin/../lib/libtorch_cpu.dylib' (no such file), '/usr/local/lib/libtorch_cpu.dylib' (no such file), '/usr/lib/libtorch_cpu.dylib' (no such file, not in dyld cache)
ImportError: dlopen(/Users/morenolq/miniconda3/lib/python3.9/site-packages/torch/_C.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libtorch_cpu.dylib
  Referenced from: <BA93ABA0-52DE-3A68-8181-9B1B82C6F0AF> /Users/morenolq/miniconda3/lib/python3.9/site-packages/torch/lib/libtorch_python.dylib
  Reason: tried: '/Users/morenolq/miniconda3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib' (no such file), '/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/Users/morenolq/miniconda3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib' (no such file), '/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/distiller/project/miniconda/envs/wheel_py39/lib/libtorch_cpu.dylib' (no such file), '/Users/morenolq/miniconda3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib' (no such file), '/Users/morenolq/miniconda3/bin/../lib/libtorch_cpu.dylib' (no such file), '/Users/morenolq/miniconda3/bin/../lib/libtorch_cpu.dylib' (no such file), '/usr/local/lib/libtorch_cpu.dylib' (no such file), '/usr/lib/libtorch_cpu.dylib' (no such file, not in dyld cache)

